### PR TITLE
Updated the patch for material for mkdocs v9.4+

### LINKED ISSUE #56: Patch for mkdocs-material 9.5.2 not working
I did not track this down in detail, but it seems the patch for at least mkdocs-material 9.5.2 is no longer correct.
The most similar path I found in the current structure of mkdocs-material is `src/templates/assets/javascripts/browser/request` instead of `src/assets/javascripts/browser/request` .
I made the change and am still facing errors... this tipe of development is far from my range of (current) knowledge and that's why I can't provide better input or even propose a PR.
Anyway, this is the error I got after making the modifications to the path mentioned above:
```
$ patch -p 0 < material_browser_request9.patch
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/templates/assets/javascripts/browser/request/index.ts
Hunk #1 FAILED at 26.
Hunk #2 FAILED at 75.
2 out of 2 hunks FAILED -- saving rejects to file src/templates/assets/javascripts/browser/request/index.ts.rej
```

### PR DESCRIPTION
**Pull request by deponovo**
Closes #56

### CODE REVIEW

**Comment by unverbuggt** [comment]
Hi,

I've tested your patch in material 9.5.2, but it doesn't seem to work correctly (produces errors in javascript window). Maybe we need to copy the `return request(url, options)` part of the original source to the `} else {` part. What I mean is:

this:
```
  } else {
    return request(url, options)
      .pipe(
        switchMap(res => res.text()),
        map(body => JSON.parse(body) as T),
        shareReplay(1)
      )
  }
```

instead of that:
```
  } else {
    return request(url, options)
      .pipe(
        switchMap(res => res.json()),
        shareReplay(1)
      )
  }
```

It would be good to also check out @ttran2's [patches](https://github.com/ttran2/mkdocs-material/commits/support-decryption). Maybe they are a better/cleaner way, but I didn't dive into it, yet.

**Comment by deponovo** [comment]
I am not a javascript developer. I can try your suggestion, but I can't review the patches from ttran2.

**Comment by unverbuggt** [comment]
The abomination of a language in which material is coded is called typescript. Looks like we need to mimic whatever `map(body => JSON.parse(body) as T),` does...

**Comment by unverbuggt** [comment]
This patch fixes it for me, please test and add this to your pull request:

```patch
--- src/templates/assets/javascripts/browser/request/index.ts	2023-12-11 16:21:03.000000000 +0100
+++ src/templates/assets/javascripts/browser/request/index.ts.encryptcontent	2023-12-16 19:57:45.611514178 +0100
@@ -24,6 +24,9 @@
   Observable,
   Subject,
   map,
+  tap,
+  of,
+  throwError,
   shareReplay,
   switchMap
 } from "rxjs"
@@ -117,12 +120,41 @@
 export function requestJSON<T>(
   url: URL | string, options?: Options
 ): Observable<T> {
-  return request(url, options)
-    .pipe(
-      switchMap(res => res.text()),
-      map(body => JSON.parse(body) as T),
-      shareReplay(1)
-    )
+  /* Hack to enable search Index decryption */
+  if (url.href.endsWith('/search_index.json')) {
+    const encryptcontentIndexKey = 'encryptcontent-index';
+    const encryptcontentIndex = sessionStorage.getItem(encryptcontentIndexKey);
+
+    if (encryptcontentIndex) {
+      // if already available in sessionStorage return Observable JSON data
+      try {
+        const parsedData = JSON.parse(encryptcontentIndex) as T;
+        return of(parsedData);
+      } catch (error) {
+        console.error('Error parsing encryptcontent-index:', error);
+        return throwError(error);
+      }
+    } else {
+      // if not yet available in sessionStorage request JSON data
+      return request(url, options).pipe(
+        switchMap(res => res.text()),
+        map(body => JSON.parse(body) as T),
+        tap((jsonData) => {
+          // and save them to sessionstorage
+          sessionStorage.setItem(encryptcontentIndexKey, JSON.stringify(jsonData));
+        }),
+        shareReplay(1)
+      );
+    }
+  } else {
+    return request(url, options)
+      .pipe(
+        switchMap(res => res.text()),
+        map(body => JSON.parse(body) as T),
+        shareReplay(1)
+      )
+  }
 }
 
 /**
```

**Comment by deponovo** [comment]
Tested and working

**Pull request merged**
